pipeline {
    agent any
    environment {
        INSTALL = "$WORKSPACE/install.sh"
        ENV = "$WORKSPACE/env.sh"
    }
    stages {
        stage("Env") {
            steps {
                sh 'chmod 755 $INSTALL $ENV'
            }
        }
        stage('Build') {
            parallel {
                stage('Build API') {
                    steps {
                        sh '$INSTALL api --build'
                    }
                    post {
                        failure {
                            echo('Building API failed. See logs for more details.')
                        }
                    }
                }
                stage('Build UI') {
                    steps {
                            sh '$INSTALL ui --build'
                    }
                    post {
                        failure {
                            echo('Building UI failed. See logs for more details.')
                        }
                    }
                }
            }
        }
        stage('Unit tests') {
            parallel {
                stage('API tests') {
                    steps {
                        sh '$INSTALL api --test'
                    }
                    post {
                        failure {
                            echo('API unit tests failed. See logs for more details.')
                        }
                    }
                }
                // Angluar app tests must be disabled for now. There are timeouts that
                // result in failure when executing those tests in Jenkins.
                // Issue hasn't been observed when running tests locally.
                /* stage('UI tests') {
                    steps {
                            sh '$INSTALL ui --test'
                    }
                    post {
                        failure {
                            echo('UI unit tests failed. See logs for more details.')
                        }
                    }
                } */
            }      
        }
    }
    post {
        always {
           sh 'docker system prune -f'
        }
    }
}
