version: '3.1'
services:
  journalapp-api:
    image: journalapp_api
    build:
      context: ${PWD}/JournalApi
      dockerfile: ${PWD}/.docker/Dockerfile.api
    container_name: journalapp_api
    restart: always
    ports:
      - 5000:5000
    environment:
      MongoDB__Host: journal-mongo
    depends_on:
      - journal-mongo
  journalapp-ui:
    image: journalapp_ui
    build:
        context: ${PWD}/JournalApp
        dockerfile: ${PWD}/.docker/Dockerfile.ui
    container_name: journalapp_ui
    restart: always
    ports:
      - 8888:80
    depends_on:
      - journalapp-api
  journal-mongo:
    image: mongo
    container_name: journal_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  journal-mongo-express:
    image: mongo-express
    container_name: journal_mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - journal-mongo