FROM node:10-alpine

ARG UID=1000
ARG USER=dev

ENV CHROME_BIN="/usr/bin/chromium-browser"

RUN deluser --remove-home node
RUN adduser --disabled-password --uid=${UID} ${USER}

RUN npm install -g @angular/cli

RUN apk add --no-cache  chromium --repository=http://dl-cdn.alpinelinux.org/alpine/v3.10/main

USER $USER

WORKDIR /src

EXPOSE 4200

CMD ["/bin/sh"]